name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-frontend-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Backend setup + cache
      - name: Set up Node.js (backend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./EmailServer/package-lock.json

      - name: Install backend dependencies
        working-directory: ./EmailServer
        run: npm install

      - name: Run backend tests
        working-directory: ./EmailServer
        run: npm test

      # ✅ Frontend setup + cache
      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./EmailClient/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./EmailClient
        run: npm install

      - name: Build frontend
        working-directory: ./EmailClient
        run: npm run build
